name: push-to-main
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-20.04
        environment: dev
        permissions:
            id-token: write
            contents: read
        steps:
            -   name: github-checkout
                uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
            -   name: aws-configure-credentials
                uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
                with:
                    role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                    aws-region: ${{ secrets.AWS_REGION }}
            -   name: aws-check-credentials
                run: aws sts get-caller-identity
