name: Example
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-20.04
        environment: dev
        permissions:
            id-token: write
            contents: read
        steps:
            -   name: Checkout
                uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
            -   name: Configure AWS credentials from Test account
                uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
                with:
                    role-to-assume: ${{ secrets.AWS_ROLE_NAME }}
                    aws-region: ${{ secrets.AWS_REGION }}
            -   name: Check AWS credentials
                run: aws sts get-caller-identity
